
spring:
  application:
    name: ecommerce-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practicejpa?serverTimezone=America/Mexico_City
    username: dev
    password: 2GuAAtkdwQY0QBRbw9wRtpnqVzfTGPH9
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create